export const gameState = {
    seed: null, 
    mode: "overworld", 
    
    // Player Position in the World
    player: {
        col: 0, 
        row: 0,
        direction: 'down' 
    },

    world: {
        // We removed the hardcoded 'procedural_forest' mapId
        // because the WorldManager now relies on the global seed + coordinates.
        currentBiomeId: null, // (Optional) Useful for UI: 'PLAINS', 'DESERT'
        time: 0, 
        day: 1,
        changes: {}, 
        discoveredChunks: [] 
    },

    party: {
        // Shared Inventory (Backpack)
        inventory: [], 
        currency: 0,
        
        // The Characters
        members: []
    },

    // ----------------------------------------
    // NON-COMBAT ENCOUNTERS (Text / Interacts)
    // ----------------------------------------
    encounter: {
        activeData: null,    
        currentStageId: null, 
        history: [],
        context: { col: null, row: null, objectId: null } 
    },

    // ----------------------------------------
    // COMBAT STATE (New)
    // ----------------------------------------
    // Holds data specifically when mode === 'battle'
    battle: {
        isActive: false,
        enemies: [],      // The roster of enemies generated by the BiomeModel
        turnQueue: [],    // Who acts next
        roundNumber: 1
    },

    ui: {
        selectedDecisionIndex: 0, 
        isMenuOpen: false
    }
};